### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [tammybeams/prj-rev-bwfs-dasmoto#3]
Overall met excellent..

In this first project I look at two main criteria with the goal to correct these issues now so they do not appear later as the projects increase in complexity.

Is the html organized and manage well using divs and classes/ids.

Div usage needs to become a practice.  Regardless you did really good on this project.

I would like to add excellent usage on multiple classes, I rarely see it on this first project.

Second is the css efficient and not overly repetitive.

Great use of efficiency, avoided the common mistakes I see in this first project completely.

As I stated earlier great use of multiple classes.  This gives you much more control and flexibility over your css.

To prepare you for upcoming projects, go to flexboxfroggy.com, see how far you can get. The later projects use flexbox heavily.

**Comment by tammybeams** [comment]
Thank you for the helpful feedback!  I see what you are saying about the "font" naming and definitely understand the "div" concept now.
